### ISSUE TITLE
Function geometryToCells not working correctly when geometry crosses antimeridian

### ISSUE THREAD

**Issue by moicalcob** [CartoDB/quadbin-js#12]
When trying to generate the quadbins for the following polygon:

![Screenshot 2023-03-29 at 17 13 11](https://user-images.githubusercontent.com/56086628/232039228-5c63d768-b5bd-4a1d-af5e-053c90a9e939.png)

I'm obtaining a weird behaviour, as can be checked when visualizing the generated result:

![Screenshot 2023-03-29 at 17 13 47](https://user-images.githubusercontent.com/56086628/232039332-537c0006-77e7-4fe1-83b5-7a8a242b1e2e.png)

Sharing [this JSFiddle](https://jsfiddle.net/wmLtx0hj/15/) where you can check the actual behaviour, with a map comparing the GeoJSON polygon used to generate the quadbins and the obtained result. Hope that it will be useful! 😄

**Comment by felixpalmer** [comment]
Your longitudes are smaller than -180, which is not generally valid in GeoJson. When you have a geometry crossing the antimeridian the safest way to deal with it is to split it in two. 

That said, deck.gl is able to draw this non-standard GeoJSON so it does make sense to support in the this library also. I will work on a fix
