### ISSUE TITLE
Fix module exports

### ISSUE THREAD

**Issue by menusal** [CartoDB/quadbin-js#6]
## Expected Behavior
Import library correctly

## Actual Behavior
When importing the library into a ReactJS project, show this error:

![image](https://user-images.githubusercontent.com/5357085/190143964-cd4774c6-2dc2-45d7-ad09-c823ece8b6b5.png)

`[plugin:vite:import-analysis] Failed to resolve entry for package "quadbin." The package may have incorrect main/module/exports specified in its package.json.` 

## Steps to Reproduce the Problem

  1. Import the library in ReacJS app with vite

### File  `package.json`
**Replace**: 
```
  "main": "dist/cjs/index.js",
  "module": "dist/esm/index.js",
  "types": "dist/types/index.d.js",
```
**to**
```
"main": "./dist/cjs/index.js",
"module": "./dist/umd/index.js",
"types": "./dist/src/index.d.ts",
```

**Add**

```
"exports": {
    ".": {
      "import": "./dist/umd/index.js",
      "require": "./dist/cjs/index.js"
    }
  },
```
 ### File  `tsconfig.json`

**Add**

```
"declaration": true,
```

**Comment by felixpalmer** [comment]
@menusal thanks for the report. I'm not sure if this is right though, shouldn't "module" reference the esm build? I've searched around for a similar package and came up with https://github.com/immerjs/immer/blob/master/package.json

I'll try adding the `exports` section as they have there
